### ISSUE TITLE
Use ca-certificates-java package's hooks

### ISSUE THREAD

**Issue by mbergumi** [debops/ansible-java#4]
When both debops_service_pki and _java are installed, the hooks in this package would ensure the key/cacert JKS are updated along. That would let the java application trust the internal root signed certificates

**Comment by drybjed** [comment]
Sounds good. I'll check it out and add it to the list of base packages. Thanks for the hint. :-)

**Comment by mbergumi** [comment]
I owed it to you. Although make sure the package does as advertised. I
haven't already.
